### ISSUE TITLE
Getting nib connection errors when crash submit window displayed

### ISSUE THREAD

**Issue by SmilinBrian** [bitstadium/HockeySDK-Mac#41]
If the application crashes, on next launch with Hockey Mac v. 3.0 I am getting these xib connection failures logged:

    TextExpander[42728]: Failed to connect (commentsTextFieldCell) outlet from (BITCrashReportUI) to (NSTextFieldCell): missing setter or instance variable
    TextExpander[42728]: Failed to connect (introductionTextFieldCell) outlet from (BITCrashReportUI) to (NSTextFieldCell): missing setter or instance variable
    TextExpander[42728]: Failed to connect (problemDescriptionTextFieldCell) outlet from (BITCrashReportUI) to (NSTextFieldCell): missing setter or instance variable

Have I somehow got old (2.1) resources still in my project, or is this a bug?

**Comment by anlinde** [comment]
Hi,

these warnings have been fixed in the develop branch and will be part of the next update, see here: https://github.com/bitstadium/HockeySDK-Mac/commit/0a3f363a8190980166a87a27a297047eb134500a

These are related to the UI and have no negative impact on the proper function of the SDK.

Thanks,
Andreas

**Comment by SmilinBrian** [comment]
Thanks. Crash reporting does seem to work correctly, but the log messages seemed worrisome. Happy to see nothing to worry about.
