### ISSUE TITLE
Duplicate crashes in crash group

### ISSUE THREAD

**Issue by suzukieng** [bitstadium/HockeySDK-Mac#89]
We are using HockeySDK-Mac version 3.6.0 and seeing duplicate crashes in a crash group (same Indicident Key in the crash log). The crashes arrive at different times:

![screen shot 2016-12-01 at 12 14 29](https://cloud.githubusercontent.com/assets/3542048/20791956/c8b81e1a-b7bf-11e6-89cf-e11b8fe28b0e.png)

We don't do anything special Hockeyapp-wise, apart from adding an application log (implementing the delegate). We auto submit the crash report without user interaction.

```
BITHockeyManager.sharedHockeyManager().configureWithIdentifier(AppDelegate.kHockeyAppAppId, delegate: self)
BITHockeyManager.sharedHockeyManager().crashManager.autoSubmitCrashReport = true // no user interaction
BITHockeyManager.sharedHockeyManager().startManager()
```

What can trigger this behavior? How does Hockeyapp mark a crash report as "sent"?

Background info:
Our app is registered as a launch agent for all users, and starts automatically when a user logs in/terminates when the user logs out. It is kept alive by launchd via the KeepAlive flag.

**Comment by TroubleMakerBen** [comment]
Hey Alex,
Thank you for getting in touch.
 
First, I strongly encourage you to upgrade your SDK, we're at 4.1.1 now. Using 3.6.0 might play a role here. Second, regarding your question: A crash report is "sent" if there was a server response and only then, the local crash report gets deleted. So it's possible that a crash report gets send  more then once. Which, third, usually isn't an issue because our backend does de-duplication based e.g. on the incident key.
Can you please open a ticket in our [Support](https://support.hockeyapp.net) and include your appId as well a link to the crashgroup? We'd like to take a closer look because our deduplication should prevent the issue you are seeing.

Best,
Benny

**Comment by suzukieng** [comment]
Thanks, I opened a private discussion through the support link. We want to upgrade to 4.x anyway for the user metrics, but before we upgrade and push a new release our to our customer we would like to know what is causing the duplicate crashes, and if it's something on our side, fix that.

**Comment by TroubleMakerBen** [comment]
I'm closing the issue here but if it's an SDK bug, I'll re-open it.

thx for geting in touch @suzukieng!

🖖
